// Generated by scripts/generate-responsive-images.mjs. Do not edit by hand.

export interface ResponsiveImageAsset {
  src: string;
  alt: string;
  objectPosition?: string;
  width: number;
  height: number;
  fallbackSrc: string;
  avifSrcSet: string;
  webpSrcSet: string;
  jpegSrcSet: string;
}

export const heroWeddingImage: ResponsiveImageAsset = {
  src: "/images/hero-wedding-1600.jpg",
  alt: "Matt proposing to Alison by the lake",
  objectPosition: "center",
  width: 2054,
  height: 1536,
  fallbackSrc: "/images/hero-wedding-1600.jpg",
  avifSrcSet: "/images/hero-wedding-640.avif 640w, /images/hero-wedding-960.avif 960w, /images/hero-wedding-1280.avif 1280w, /images/hero-wedding-1600.avif 1600w, /images/hero-wedding-2054.avif 2054w",
  webpSrcSet: "/images/hero-wedding-640.webp 640w, /images/hero-wedding-960.webp 960w, /images/hero-wedding-1280.webp 1280w, /images/hero-wedding-1600.webp 1600w, /images/hero-wedding-2054.webp 2054w",
  jpegSrcSet: "/images/hero-wedding-640.jpg 640w, /images/hero-wedding-960.jpg 960w, /images/hero-wedding-1280.jpg 1280w, /images/hero-wedding-1600.jpg 1600w, /images/hero-wedding-2054.jpg 2054w",
};

export const ringImage: ResponsiveImageAsset = {
  src: "/images/ring-1536.jpg",
  alt: "A close up of Alison's engagement ring",
  objectPosition: "center",
  width: 2048,
  height: 1991,
  fallbackSrc: "/images/ring-1536.jpg",
  avifSrcSet: "/images/ring-480.avif 480w, /images/ring-768.avif 768w, /images/ring-1024.avif 1024w, /images/ring-1536.avif 1536w, /images/ring-2048.avif 2048w",
  webpSrcSet: "/images/ring-480.webp 480w, /images/ring-768.webp 768w, /images/ring-1024.webp 1024w, /images/ring-1536.webp 1536w, /images/ring-2048.webp 2048w",
  jpegSrcSet: "/images/ring-480.jpg 480w, /images/ring-768.jpg 768w, /images/ring-1024.jpg 1024w, /images/ring-1536.jpg 1536w, /images/ring-2048.jpg 2048w",
};

export const smileImage: ResponsiveImageAsset = {
  src: "/images/smile-1536.jpg",
  alt: "Alison & Matt, shortly after the proposal",
  objectPosition: "center",
  width: 1536,
  height: 2304,
  fallbackSrc: "/images/smile-1536.jpg",
  avifSrcSet: "/images/smile-480.avif 480w, /images/smile-768.avif 768w, /images/smile-1024.avif 1024w, /images/smile-1536.avif 1536w",
  webpSrcSet: "/images/smile-480.webp 480w, /images/smile-768.webp 768w, /images/smile-1024.webp 1024w, /images/smile-1536.webp 1536w",
  jpegSrcSet: "/images/smile-480.jpg 480w, /images/smile-768.jpg 768w, /images/smile-1024.jpg 1024w, /images/smile-1536.jpg 1536w",
};
